---
# tasks file for nginx

- include_tasks: install.yml

- name: Clear config.
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ nginx_clear_config_files }}"
  when: nginx_clear_config or install_changed.changed

- name: Configuration.
  include_tasks: config.yml
  with_fileglob: "{{ nginx_config_fileglob }}"
  when: nginx_deploy_config
